# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 02:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('want_to_marry_within_how_many_years', models.PositiveIntegerField(blank=True, default=0)),
                ('marital_status', models.CharField(blank=True, choices=[(b'Celibataire', b'Celibataire'), (b'Marrie(e)', b'Marrie(e)'), (b'Jamais Marrie(e)', b'Jamais Marrie(e)'), (b'Divorce(e)', b'Divorce(e)'), (b'Veuf(ve)', b'Veuf(ve)')], max_length=20)),
                ('number_of_children', models.PositiveIntegerField(blank=True, default=0)),
                ('want_children', models.BooleanField(default=True)),
                ('studies_level', models.CharField(blank=True, choices=[(b'AVANT BFEM', b'AVANT BFEM'), (b'BFEM', b'BFEM'), (b'BAC', b'BAC'), (b'BAC+2', b'BAC+2'), (b'BAC+3', b'BAC+3'), (b'BAC+4', b'BAC+4'), (b'BAC+5 et plus', b'BAC+5 et plus')], max_length=30)),
                ('height', models.PositiveIntegerField(null=True)),
                ('silhouette', models.CharField(blank=True, choices=[(b'Normale', b'Normale'), (b'Sportif/ve', b'Sportif/ve'), (b'En surpoids', b'En surpoids')], max_length=30)),
                ('origin', models.CharField(blank=True, choices=[(b'Africaine', b'Africaine'), (b'Europeene', b'Europeene'), (b'Asiatique', b'Asiatique'), (b'Arabe', b'Arabe')], max_length=30)),
                ('religion', models.CharField(blank=True, choices=[(b'Musulman', b'Musulman'), (b'Chretien', b'Chretien'), (b'Autre', b'Autre')], max_length=30)),
                ('ethny', models.CharField(blank=True, choices=[(b'Wolof', b'Wolof'), (b'Peul', b'Peul'), (b'Toucouleur', b'Toucouleur'), (b'Serere', b'Serere'), (b'Diola', b'Diola'), (b'Autre', b'Autre')], max_length=30)),
                ('smoking', models.BooleanField(default=True)),
                ('confrery', models.CharField(blank=True, choices=[(b'Mouride', b'Mouride'), (b'Tidjane', b'Tidjane'), (b'Layene', b'Layene'), (b'Autre', b'Autre')], max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('min_age', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(18)])),
                ('max_age', models.PositiveIntegerField(null=True)),
                ('ideal_marital_status', models.CharField(blank=True, choices=[(b'Celibataire', b'Celibataire'), (b'Marrie(e)', b'Marrie(e)'), (b'Jamais Marrie(e)', b'Jamais Marrie(e)'), (b'Divorce(e)', b'Divorce(e)'), (b'Veuf(ve)', b'Veuf(ve)')], max_length=20)),
                ('ideal_want_children', models.BooleanField(default=True)),
                ('ideal_height', models.PositiveIntegerField(null=True)),
                ('ideal_silhouette', models.CharField(blank=True, choices=[(b'Normale', b'Normale'), (b'Sportif/ve', b'Sportif/ve'), (b'En surpoids', b'En surpoids')], max_length=30)),
                ('ideal_smoking', models.BooleanField(default=True)),
                ('ideal_confrery', models.CharField(blank=True, choices=[(b'Mouride', b'Mouride'), (b'Tidjane', b'Tidjane'), (b'Layene', b'Layene'), (b'Autre', b'Autre')], max_length=30)),
                ('ideal_religion', models.CharField(blank=True, choices=[(b'Musulman', b'Musulman'), (b'Chretien', b'Chretien'), (b'Autre', b'Autre')], max_length=30)),
                ('ideal_ethny', models.CharField(blank=True, choices=[(b'Wolof', b'Wolof'), (b'Peul', b'Peul'), (b'Toucouleur', b'Toucouleur'), (b'Serere', b'Serere'), (b'Diola', b'Diola'), (b'Autre', b'Autre')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
